export const LANDING = "/"
export const SIGN_UP = "/signup"
export const SIGN_IN = "/signin"
export const ROOT = "/"
export const ACCOUNT = "/account"
export const PASSWORD_FORGET = "/pw-forget"
export const ADMIN = "/admin"
export const ADMIN_DETAILS = "/admin/:id"

export const TESTS = "/tests"

export const LESSONS = "/lessons"
export const LESSONS_SAMPLE = LESSONS + "/sample"
export const LESSONS_LEVEL0 = LESSONS + "/level0"
export const LESSONS_LEVEL1 = LESSONS + "/level1"
export const LESSONS_LEVEL2 = LESSONS + "/level2"
export const LESSONS_LEVEL3 = LESSONS + "/level3"
