export const LANDING = "/"
export const SIGN_UP = "/signup"
export const SIGN_IN = "/signin"
export const ROOT = "/"
export const ACCOUNT = "/account"
export const PASSWORD_FORGET = "/pw-forget"
export const ADMIN = "/admin"
export const ADMIN_DETAILS = "/admin/:id"

export const LESSONS = "/lessons"
export const TESTS = "/tests"
